fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    powershell: git://github.com/puppetlabs/puppetlabs-powershell
    reboot: git://github.com/puppetlabs/puppetlabs-reboot
  symlinks:
    dialer: "#{source_dir}"