fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    powershell: git://github.com/puppetlabs/puppetlabs-powershell.git
    reboot: git://github.com/puppetlabs/puppetlabs-reboot.git
    chocolatey: git://github.com/chocolatey/puppet-chocolatey.git
  symlinks:
    dialer: "#{source_dir}"