language: ruby
rvm:
  - 2.0.0
sudo: false
env:
  - PUPPET_VERSION=3.7.3
  - RSPEC_VERSION=3.2.3
script: "rake spec SPEC_OPTS='--format documentation'"
gemfile: Gemfile
matrix:
  fast_finish: true
branches:
    only:
      - master
notifications:
  email:
    - pierrick.lozach@inin.com