language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
sudo: false
env:
  - PUPPET_VERSION=2.7
  - PUPPET_VERSION=3.2
  - PUPPET_VERSION=3.4
  - PUPPET_VERSION=3.6
  - PUPPET_VERSION=3.7
  - PUPPET_VERSION=4.0
  - RSPEC_VERSION=2.14
script: "rake validate && rake lint && rake spec SPEC_OPTS='--format documentation'"
gemfile: Gemfile
matrix:
  fast_finish: true
  exclude:
    - rvm: 1.8.7
      env: RSPEC_VERSION=2.14
    - rvm: 1.8.7
      env: PUPPET_VERSION=4.0
    - rvm: 1.9.3
      env: PUPPET_VERSION=2.7
    - rvm: 2.0.0
      env: PUPPET_VERSION=2.7
    - rvm: 2.1
      env: PUPPET_VERSION=2.7
    - rvm: 2.1
      env: PUPPET_VERSION=3.2
branches:
    only:
      - master
notifications:
  email:
    - pierrick.lozach@inin.com