sudo: false
language: ruby
script: "rake validate && rake lint && rake spec SPEC_OPTS='--format documentation'"
gemfile: Gemfile
matrix:
  fast_finish: true
  include:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 2.1.5
      env: PUPPET_GEM_VERSION="~> 3.0"
    - rvm: 2.1.5
      env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~>1.6.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 2.7.0" FACTER_GEM_VERSION="~>1.7.0"
branches:
    only:
      - master
notifications:
  email:
    - pierrick.lozach@inin.com
  env:
    - PUPPET_VERSION=3.7.3