# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
#
# Gets the latest version of a file
#
# Usage: latest_version(dir, pattern)
#
# params:
#
# - dir: path to files
# - pattern: file matching pattern
#

#require 'fileutils'

# ---- original file header ----
#
# @summary
#   Summarise what the function does here
#
Puppet::Functions.create_function(:'dialer::latest_version') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    
  	directory = args[0]
  	pattern = args[1]

  	debug "Getting latest version of " + pattern + " in " + directory
	Dir.chdir(directory)
	files = Dir.glob(pattern)

	latestversion = files.max()
	latestversion
  
  end
end
